Repository FedeZimmer/MoravecReactNative, pull requests merged in 2018-04, with the labels that each got.

#8 (2) Elevar al cuadrado: Poner superindice
  package-lock.json
  package.json
  src/actions/game_actions.js
  src/actions/operations/Addition.js
  src/actions/operations/Multiplication.js
  src/actions/operations/Operation.js
  src/actions/operations/ToSquare.js
  src/components/game/calculator/OperationDisplay.js
Labels: Cambios pendientes

#9 Bugfix: Fix Start level race condition
  src/actions/game_actions.js
  src/reducers/game_reducer.js
Labels: Aprobado

#10 Logica y mensaje distinto para cuenta realizada fuera de tiempo
  index.js
  specs/bots/MoravecPlayer.js
  specs/game_spec.js
  src/components/game/Game.js
  src/components/game/header/Header.js
  src/components/game/header/LevelState.js
  src/components/game/header/UserAnswerFeedback.js
  src/components/game/header/YouCanDoBetterMessage.js
  src/reducers/game_reducer.js
Labels: Aprobado

#11 Agregar header bar a la seleccion de niveles para poder ir para atras
  src/components/common/BackButton.js
  src/components/common/Header.js
  src/components/game/LevelSelection.js
  src/containers/GameEngine.js
  src/styles/common/styles.js
Labels: Aprobado

#12 Bug: Cuando se ingresa un valor y despues se borra, deja enviar un re…
  specs/bots/MoravecPlayer.js
  specs/game_spec.js
  src/components/game/calculator/keyboard/CalculatorKeyboard.js
  src/components/game/calculator/keyboard/EraseKey.js
  src/reducers/game_reducer.js
Labels: Aprobado, Sugerencias

#13 Solo se puede jugar siguiente nivel si tiene una estrella
  specs/bots/MoravecPlayer.js
  specs/game_spec.js
  src/components/game/LevelFinished.js
  src/components/game/LevelSelection.js
  src/components/game/PlayLevelButton.js
  src/components/game/PlayNextButton.js
  src/components/game/ReplayButton.js
  src/reducers/game_reducer.js
  src/styles/game/styles.js
Labels: Aprobado
